---
abstract: 'Romanization of Lao language'
author:
  - 'Joakim Lagerqvist <jokke@cpan.org>'
build_requires:
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::AttributeHelpers: 0
  MooseX::Params::Validate: 0
  Test::More: 0
  utf8: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-LO-Romanize
provides:
  Lingua::LO::Romanize:
    file: lib/Lingua/LO/Romanize.pm
    version: 0.10
  Lingua::LO::Romanize::Syllable:
    file: lib/Lingua/LO/Romanize/Syllable.pm
    version: 0.10
  Lingua::LO::Romanize::Types:
    file: lib/Lingua/LO/Romanize/Types.pm
    version: 0.10
  Lingua::LO::Romanize::Word:
    file: lib/Lingua/LO/Romanize/Word.pm
    version: 0.10
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
